In [3]:
pip install numpy

     |████████████████████████████████| 17.3 MB 25.1 MB/s eta 0:00:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


# *Consider the below code to answer further questions*:


In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# Q1.

Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.


## Answer

Yes, there is a difference in the data type of variables `list_` and `array_list`.

`list_` is a Python list data type, whereas `array_list` is a numpy array data type.

To print the data types of both the variables, you can use the type() function in Python as follows:

In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
list_

['1', '2', '3', '4', '5']

In [6]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

Here, the `type()` function returns the data type of the variable passed as an argument. The first `print()` statement returns the data type of the `list_` variable as list. The second `print()` statement returns the data type of the `array_list` variable as `numpy.ndarray`.

# Q2. 

Write a code to print the data type of each and every element of both the variables list_ and
arra_list.


## Answer

In [7]:
# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Here, the `for` loop iterates through each element in `list_` and `array_list` and prints its data type using the `type()` function. Note that the data type of each element in `list_` is `str`, while the data type of each element in `array_list` is `numpy.str_`.

# Q3. 

Considering the following changes in the variable, array_list:


In [8]:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.


## Answer

Yes, there will be a difference in the data type of the elements present in `list_` and `array_list` when `array_list` is created using the `dtype=int` argument. The elements in `array_list` will be of integer data type (`int`) instead of string data type (`numpy.str_`).

Here's the updated code to print the data types of each element in both `list_` and `array_list` after the change:

In [9]:
# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Here, the data type of each element in `list_` is still `str`, while the data type of each element in `array_list` is now `numpy.int64`.

# *Consider the below code to answer further questions:*

In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

# Q4. 

Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size


## Answer

In [12]:
# Find shape of num_array
# (i) shape
shape = num_array.shape
print("Shape of num_array:", shape)

# Find size of num_array
# (ii) size
size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


Here, the `shape` attribute of `num_array` returns a tuple that represents the number of rows and columns in the array. In this case, the `shape` of `num_array` is `(2, 3)`, which means that it has 2 rows and 3 columns.

The `size` attribute of `num_array` returns the total number of elements in the array. In this case, the size of `num_array` is `6`, which is the product of the number of rows and columns.

# Q5. 

Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]


## Answer

In [13]:
import numpy as np

# Create a numpy array of zeros with shape (3,3)
zeros_array = np.zeros(shape=(3,3))

# Print the zeros array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. 

Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

## Answer

In [16]:
import numpy as np

I = np.eye(5)
print('Identity Matrix:')
print(f'I = {I}')

Identity Matrix:
I = [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


*********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************